services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/tarefa6.conf:/etc/apache2/sites-enabled/tarefa6.conf
      - ./exemplo.lan:/opt/web/exemplo.lan
      - ./omeusitio.lan:/opt/web/omeusitio.lan
      - ./novositio.lan:/opt/web/novositio.lan
      - ./certificados/meusitio.key:/etc/ssl/private/meusitio.key
      - ./certificados/meusitio.pem:/etc/ssl/certs/meusitio.pem
      - ./acceso.log:/var/log/apache2/omeusitio.lan/acceso.log

    networks:
      redeapache:
        ipv4_address: 192.168.58.100
        aliases:
          - exemplo.lan
          - www.exemplo.lan
          - eq1.exemplo.lan
          - www.omeusitio.lan
          - omeusitio.lan
          - novositio.lan
          - www.novositio.lan
    develop:
      watch:
        - path: ./apache/test1.conf
          action: restart

  cliente:
    image: brunosct/debian12-cliente-firefox
    hostname: cliente
    networks:
      redeapache:
        ipv4_address: 192.168.58.127
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  redeapache:
    ipam:
      config:
        - subnet: 192.168.58.0/24